version: "3.8"

services:
  app: 
    build: .
    ports:
      - 5050:5050
    restart: always
    environment:
      - MONGO_URL=mongodb://db/node
    depends_on:
      - db
  
  db:
    container_name: db
    image: mongo:4.4
    ports:
      - 27017:27017
    restart: always